# Generated by Django 4.1.3 on 2022-11-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director',
            new_name='Directores',
        ),
        migrations.RenameModel(
            old_name='Genero',
            new_name='Generos',
        ),
        migrations.RenameModel(
            old_name='Pelicula',
            new_name='Peliculas',
        ),
    ]
