# Generated by Django 4.1.3 on 2022-11-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_director_directores_rename_genero_generos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directores',
            new_name='Director',
        ),
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Pelicula',
        ),
    ]
