# Generated by Django 4.1.3 on 2022-11-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_directores_director_rename_generos_genero_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelicula',
            new_name='Film',
        ),
        migrations.RenameModel(
            old_name='Genero',
            new_name='Genere',
        ),
    ]
