# Generated by Django 4.1.3 on 2022-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_rename_pelicula_film_rename_genero_genere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='periodo_actividad',
            new_name='periodo_actividad_desde',
        ),
        migrations.AddField(
            model_name='director',
            name='periodo_actividad_hasta',
            field=models.DateField(blank=True, help_text='Periodo de actividad del director', null=True),
        ),
    ]
